### ISSUE TITLE
strsvr_qt producing corrupt files

### ISSUE THREAD

**Issue by GPSFan** [JensReimann/RTKLIB#8] opened 2017-01-15 23:38 UTC
While doing some tests with a 3DR telemetry radio I found that the resulting file had what appeared to be large gaps in the data. On further investigation I found that the data was being corrupted.
The Windows version produces a non corrupted file using the same radios and setup.
I found that having the input stream connected to a serial port with no data coming in, that the output file started at zero bytes and grew by about 22 bytes per second.
Looking further, I found that if you used strsvr_qt to copy ( no conversion) a file, the resulting file did not match the original. The amount varied maybe related to how large the input file was.
While I was doing the telemetry tests I noticed that the bytes stored counter started the same as the bytes received counter but diverged as time went by. The data was arriving at 1 sec intervals and I could see the stored counter climb after each burst of data was received.
Data rate was 57600 8 bits no parity.
If the output file is null you can see the results on stdout.

**Comment by JensReimann** [comment] 2017-01-17 15:51
Fixed. The issue was caused by a wrong initialization of a variable resulting in periodical transmission of garbage data to the output. Same issue was fixed in rtknavi_qt.

**Comment by GPSFan** [comment] 2017-01-17 20:08
strsvr_qt now produces files without corruption, except at the end of the file when it is closed by pressing the Stop button. Several extra bytes are written to the file. I tested this by stopping the serial stream after 15 minutes of data collection. The bytes received and bytes written counters were identical. I then pressed the Stop button and the bytes written counter advanced by several bytes.
As for rtknavi_qt, when recompiled, it segfaults as soon as the start button is pressed. I backed out the only change, recompiled and it now functions again.

**Comment by JensReimann** [comment] 2017-01-18 15:19
The extra data added while stopping has been fixed. Hopefully the crash of rtknavi_qt is also fixed. Please give it a try.

**Comment by GPSFan** [comment] 2017-01-18 16:51
Initial tests on rtknavi_qt show the segfault problem resolved.
Initial tests on strsvt_qt show the original problem as well as the subsequent problem resolved.
More tests to come.
Thanks for the fixes...

**Closed as completed** 2017-02-08 14:49 UTC

**Comment by GPSFan** [comment] 2017-02-08 15:11
Sorry, I should have closed this issue a while ago. Got busy. Subsequent test showed no further issues.
